version: "3.8"
services:
  server:
    build:
      context: "./"
      dockerfile: "./docker-files/nginx.dockerfile"
    ports: 
      - '8000:80'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './src:/var/www/html'
    depends_on:
      - php
      - mariadb 
      - adminer
  php:
    build:
      context: "./"
      dockerfile: "./docker-files/php.dockerfile"
    volumes:
      - './src:/var/www/html'
  mariadb:
    image: mariadb
    env_file: './env/mariadb.env'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  composer:
    build:
      context: "./"
      dockerfile: "./docker-files/composer.dockerfile"